---
  - name: install base packages
    package:
      state: latest
      name:
        - ansible
          #- ansible-python3
        - arandr
        - bash-completion
        - blueman
        #      - brasero
        #      - brasero-nautilus
        #      - chromaprint-tools
        #      - copr-cli
        - docker
        #      - epiphany
        #      - fedpkg
        #      - fedora-packager
        - feh
        #      - ffmpeg
        - firewalld
        #      - flash-plugin
        - git
        #      - gnome-shell-extension-pomodoro
        #      - gobby05
        #      - golang
        #      - google-roboto-slab-#onts
        #      - gstreamer-ffmpeg
        #      - gstreamer1-plugins-bad-free-extras
        #      - gstreamer1-plugins-bad-nonfree
        #      - gstreamer1-plugins-ugly
        - hexchat
        #      - htop
        - inkscape
        - i3
          #- java-11-openjdk
        #      - jpegoptim
        #      - jq
        #      - libselinux-python
        #- libvirt
        #- libvirt-devel
        #      - meld
        #      - mpv
        #      - nautilus-dropbox
        - network-manager
        #      - overpass-fonts
        #      - overpass-mono-fonts
        #      - pandoc
        #      - pass
        #      - pavucontrol
        #      - picard
        #      - podman
        #      - powerline-fonts
        - pulseaudio-utils
        #      - python2-flake8
        #      - python3-flake8
        #      - ripright
        #      - smartmontools
        #- spotify-client
        #      - strace
        #      - sublime-text
        - telegram-desktop
        #      - typetype-molot-fonts
        - ufw
        #      - '@vagrant'
        #      - vagrant-doc
        #      - vagrant-sshfs
        #      - '@virtualization'
        #      - visualboyadvance-m
        #      - youtube-dl
        - virtualbox
